### ISSUE TITLE
Spec bug

### ISSUE THREAD

**Issue by helqless** [HGLabor/HGLaborDuels#11]
Wenn man in einer party spec und sich umbringt dann kann man items aufsammeln und blöcke placen und irgendwie wird man in lobby tpt und kann dort fliegen und blöcke abbauen very game breaking bug must fix

**Comment by BestAutoyes** [comment]
wie jetzt, wenn du specst und dich dann umbringst?

**Comment by helqless** [comment]
> wie jetzt, wenn du specst und dich dann umbringst?

Wenn du ein party hast und einen z.B. 3v1 und dich am anfang der Runde umbringst kannst Items aufsammeln fliegen und Schaden bekommen. Wenn du dann nochmal stirbst kommt du zur 1v1 Lobby wo du dann auch fliegen kannst und blöcke abbauen kannst.

**Comment by helqless** [comment]
Hier ein Video damit du es besser verstehst.
https://youtu.be/-wd7SXANB48
