### ISSUE TITLE
Items gehen nicht kaputt

### ISSUE THREAD

**Issue by helqless** [HGLabor/HGLaborDuels#6]
z.B. in SG geht das feuerzeug nicht kaputt und somit kann man feuerteufel spielen 😡

**Comment by helqless** [comment]
![2021-04-28_11 44 52](https://user-images.githubusercontent.com/72995294/116383595-45946780-a817-11eb-9b31-2090ee3114ea.png)

**Comment by BestAutoyes** [comment]
Sollte nachher gefixt sein
