### ISSUE TITLE
1.8 & 1.16 KB Queue

### ISSUE THREAD

**Issue by byMysterio** [HGLabor/HGLaborDuels#7]
Da der Sinn einer Queue ist gegen random Leute zu spielen, sollte man diese in 1.8 und 1.16 KB unterteilen, da man anders als beim normalen 1v1 nicht einen Gegner hat, den man bitten kann das KB einzustellen, sondern potentiell alle Leute, die queuen.

**Comment by BestAutoyes** [comment]
Also lieber 2 queues mit einem Spieler als eine queue mit 2 spielern?
Dann findet man gar keine Gegner mehr

**Comment by HitzlikeaBanana** [comment]
Finde es wie es gerade ist besser so. Die meisten die auf 1v1 joinen tun das um gegen einen Freund zu spielen, da kann man ja fragen. Und damit die leute die einfach nur "Queuen?" auch fights bekommen finde ich es so fine. (Falls es bald mehr Spieler auf Labor bzw. auf 1v1 geben wird, wäre es wiederum besser die queues zu splitten)
