### ISSUE TITLE
Absorbtionherzen verbuggt

### ISSUE THREAD

**Issue by realjarek** [HGLabor/HGLaborDuels#9]
wenn man nen 1v1 mit gaps spielt und dannauch in eine soup 1v1 geht hat man manchmal noch verbuggte Absorbtionherzen die einem zwar angezeigt werden aber eigentlich nicht da sind ist ein bisschen nervig

**Comment by BestAutoyes** [comment]
92beaed6d22aa016ed8715b1f87d5801f40e8454
